name: Pilot Wings64 (North America)
sha1: ec771aedf54ee1b214c25404fb4ec51cfd43191a
options:
  basename: pilotwings64
  target_path: config/us/baserom.us.z64
  elf_path: build/pilotwings64.elf
  base_path: ../..
  platform: n64
  compiler: IDO

  asm_path: asm
  src_path: src
  asset_path: bin
  build_path: build
  create_asm_dependencies: True
  asm_emit_size_directive: True
  disasm_unknown: True

  ld_script_path: build/pilotwings64.us.ld
  ld_dependencies: True

  find_file_boundaries: True
  header_encoding: ASCII

  o_as_suffix: True
  use_legacy_include_asm: False
  mips_abi_float_regs: o32

  # section_order: [".text", ".data", ".rodata", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/us/sym/symbol_addrs.txt
    - config/us/sym/libultra_symbols.txt
  reloc_addrs_path:
    - config/us/sym/reloc_addrs.txt

  undefined_funcs_auto_path: build/splat_out/us/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/splat_out/us/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  # string_encoding: ASCII
  # data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  libultra_symbols: True
  hardware_regs: True
  gfx_ucode: f3d
  migrate_rodata_to_functions: True

segments:
  - name: header
    type: header
    start: 0x0

  - name: ipl3
    type: bin
    start: 0x40

  - name: entry
    type: code
    start: 0x1000
    vram: 0x80200050
    subsegments:
      - [0x1000, hasm, entrypoint]

  - name: kernel
    type: code
    start: 0x1050
    vram: 0x802000A0
    follows_vram: entry
    subsegments:
      - [0x01050, c, kernel/code_1050]
      - [0x01300, c, kernel/code_1300]
      - [0x02130, c, kernel/code_2130]
      - [0x03D50, c, kernel/code_3D50]
      - [0x04850, c, kernel/code_4850]
      - [0x05690, c, kernel/code_5690]
      - [0x058E0, c, kernel/code_58E0]
      - [0x06F80, c, kernel/code_6F80]
      - [0x07150, c, kernel/code_7150]
      - [0x08170, c, kernel/code_8170]
      - [0x177A0, c, kernel/code_177A0]
      - [0x19170, c, kernel/code_19170]
      - [0x19B50, c, kernel/code_19B50]
      - [0x1AF80, c, kernel/code_1AF80]
      - [0x200B0, c, kernel/code_200B0]
      - [0x21910, c, kernel/code_21910]
      - [0x25250, c, kernel/code_25250]
      - [0x25650, c, kernel/code_25650]
      - [0x28EE0, c, kernel/code_28EE0]
      - [0x2AE50, c, kernel/code_2AE50]
      - [0x2B370, c, kernel/code_2B370]
      - [0x2C050, c, kernel/code_2C050]
      - [0x2D490, c, kernel/code_2D490]
      - [0x2EEA0, c, kernel/code_2EEA0]
      - [0x2FE40, c, kernel/code_2FE40]
      - [0x30DF0, c, kernel/code_30DF0]
      - [0x30EA0, c, kernel/code_30EA0]
      - [0x310E0, c, kernel/code_310E0]
      - [0x32480, c, kernel/code_32480]
      - [0x32590, c, kernel/code_32590]
      - [0x329C0, hasm, kernel/code_329C0]
      - [0x32A70, c, kernel/code_32A70]
      - [0x35450, c, kernel/code_35450]
      - [0x35470, c, kernel/code_35470]
      - [0x354E0, c, kernel/code_354E0]
      - [0x355D0, c, kernel/code_355D0]
      - [0x35640, c, kernel/code_35640]
      - [0x356A0, c, kernel/code_356A0]
      - [0x35700, c, kernel/code_35700]
      - [0x35760, c, kernel/code_35760]
      - [0x357C0, c, kernel/code_357C0]
      - [0x35800, c, kernel/code_35800]
      - [0x35F10, c, kernel/code_35F10]
      - [0x37140, c, kernel/code_37140]
      - [0x37290, c, kernel/code_37290]
      - [0x372F0, c, kernel/code_372F0]
      - [0x37540, c, kernel/code_37540]
      - [0x37790, c, kernel/code_37790]
      - [0x378E0, c, kernel/code_378E0]
      - [0x37B70, c, kernel/code_37B70]
      - [0x37BF0, c, kernel/code_37BF0]
      - [0x37CA0, c, kernel/code_37CA0]
      - [0x37CB0, c, kernel/code_37CB0]
      - [0x38490, c, kernel/code_38490]
      - [0x384D0, c, kernel/code_384D0]
      - [0x384E0, c, kernel/code_384E0]
      - [0x38FA0, c, kernel/code_38FA0]
      - [0x38FE0, c, kernel/code_38FE0]
      - [0x39080, c, kernel/code_39080]
      - [0x390C0, c, kernel/code_390C0]
      - [0x39100, c, kernel/code_39100]
      - [0x3B730, c, kernel/code_3B730]
      - [0x3B760, c, kernel/code_3B760]
      - [0x3B7D0, c, kernel/code_3B7D0]
      - [0x3B7E0, c, kernel/code_3B7E0]
      - [0x3B8D0, c, kernel/code_3B8D0]
      - [0x3BA90, c, kernel/code_3BA90]
      - [0x3BDD0, c, kernel/code_3BDD0]
      - [0x3BE50, c, kernel/code_3BE50]
      - [0x3C110, c, kernel/code_3C110]
      - [0x3C4F0, c, kernel/code_3C4F0]
      - [0x3C560, c, kernel/code_3C560]
      - [0x3C5D0, c, kernel/code_3C5D0]
      - [0x3C640, c, kernel/code_3C640]
      - [0x3C820, c, kernel/code_3C820]
      - [0x3C960, c, kernel/code_3C960]
      - [0x3C9D0, c, kernel/code_3C9D0]
      - [0x3CC60, c, kernel/code_3CC60]
      - [0x3CC70, c, kernel/code_3CC70]
      - [0x3CDF0, c, kernel/code_3CDF0]
      - [0x3CFB0, c, kernel/code_3CFB0]
      - [0x3D5D0, c, kernel/code_3D5D0]
      - [0x3D680, c, kernel/code_3D680]
      - [0x3D810, c, kernel/code_3D810]
      - [0x3DDD0, c, kernel/code_3DDD0]
      - [0x3DE60, c, kernel/code_3DE60]
      - [0x3DEF0, c, kernel/code_3DEF0]
      - [0x3DF90, c, kernel/code_3DF90]
      - [0x3E020, c, kernel/code_3E020]
      - [0x3E0C0, c, kernel/code_3E0C0]
      - [0x3E140, c, kernel/code_3E140]
      - [0x3FB90, c, kernel/code_3FB90]
      - [0x3FCD0, c, kernel/code_3FCD0]
      - [0x3FD10, c, kernel/code_3FD10]
      - [0x406F0, c, kernel/code_406F0]
      - [0x40700, c, kernel/code_40700]
      - [0x407C0, c, kernel/code_407C0]
      - [0x40F70, c, kernel/code_40F70]
      - [0x41010, c, kernel/code_41010]
      - [0x41CB0, c, kernel/code_41CB0]
      - [0x41FB0, c, kernel/code_41FB0]
      - [0x42C10, c, kernel/code_42C10]
      - [0x42D20, c, kernel/code_42D20]
      - [0x42F60, c, kernel/code_42F60]
      - [0x42F80, c, kernel/code_42F80]
      - [0x43360, c, kernel/code_43360]
      - [0x43370, c, kernel/code_43370]
      - [0x433B0, c, kernel/code_433B0]
      - [0x43440, c, kernel/code_43440]
      - [0x43470, c, kernel/code_43470]
      - [0x43890, c, kernel/code_43890]
      - [0x438A0, c, kernel/code_438A0]
      - [0x43C00, c, kernel/code_43C00]
      - [0x43C10, c, kernel/code_43C10]
      - [0x443F0, c, kernel/code_443F0]
      - [0x444D0, c, kernel/code_444D0]
      - [0x44580, c, kernel/code_44580]
      - [0x44600, c, kernel/code_44600]
      - [0x44660, c, kernel/code_44660]
      - [0x44700, c, kernel/code_44700]
      - [0x44960, c, kernel/code_44960]
      - [0x449F0, c, kernel/code_449F0]
      - [0x44AA0, c, kernel/code_44AA0]
      - [0x44B20, c, kernel/code_44B20]
      - [0x455D0, c, kernel/code_455D0]
      - [0x45700, c, kernel/code_45700]
      - [0x45800, c, kernel/code_45800]
      - [0x45820, c, kernel/code_45820]
      - [0x46430, c, kernel/code_46430]
      - [0x46440, c, kernel/code_46440]
      - [0x46470, c, kernel/code_46470]
      - [0x46480, c, kernel/code_46480]

      - [0x464E0, textbin, rspboot]
      - [0x465B0, textbin, f3d]

      - [0x475B0, data]
      - [0x479E0, data]
      - [0x48E10, data]
      - [0x49C30, data]
      - [0x49D60, data]
      - [0x49D80, data]
      - [0x49D90, data]
      - [0x49DC0, data]
      - [0x49DD0, data]
      - [0x49E50, data]
      - [0x4A0F0, data]
      - [0x4A160, data]
      - [0x4A190, data]
      - [0x4A1E0, data]
      - [0x4A200, data]
      - [0x4C210, data]
      - [0x4C270, data]
      - [0x4C280, data]
      - [0x4C580, data]
      - [0x4C590, data]
      - [0x4C5C0, data]
      - [0x4C5F0, data]
      - [0x4C620, data]
      - [0x4C660, data]
      - [0x4C690, data]
      - [0x4C6C0, data]
      - [0x4C6F0, data]
      - [0x4C730, data]
      - [0x4C740, data]
      - [0x4C750, data]
      - [0x4C760, data]
      - [0x4C780, data]
      - [0x4D050, data]
      - [0x4D070, data]
      - [0x4D080, data]
      - [0x4D0A0, data]
      - [0x4D0C0, data]
      - [0x4D0F0, data]
      - [0x4D120, data]
      - [0x4D270, data]
      - [0x4D2C0, data]
      - [0x4D410, data]
      - [0x4D420, data]
      - [0x4D430, data]
      - [0x4D440, data]
      - [0x4D450, .rodata, kernel/code_1050]
      - [0x4D540, .rodata, kernel/code_1300]
      - [0x4D5E0, .rodata, kernel/code_2130]
      - [0x4DBF0, .rodata, kernel/code_3D50]
      - [0x4DC90, .rodata, kernel/code_4850]
      - [0x4DCE0, .rodata, kernel/code_5690]
      - [0x4DD10, .rodata, kernel/code_58E0]
      - [0x4DDC0, .rodata, kernel/code_6F80]
      - [0x4DDF0, .rodata, kernel/code_7150]
      - [0x4DE10, .rodata, kernel/code_8170]
      - [0x4E370, .rodata, kernel/code_177A0]
      - [0x4E620, .rodata, kernel/code_19170]
      - [0x4E780, .rodata, kernel/code_19B50]
      - [0x4E830, .rodata, kernel/code_1AF80]
      - [0x4EB30, .rodata, kernel/code_200B0]
      - [0x4EBD0, .rodata, kernel/code_21910]
      - [0x4EEF0, .rodata, kernel/code_25250]
      - [0x4EF70, .rodata, kernel/code_25650]
      - [0x4F280, .rodata, kernel/code_28EE0]
      - [0x4F350, .rodata, kernel/code_2AE50]
      - [0x4F3B0, .rodata, kernel/code_2B370]
      - [0x4F630, .rodata, kernel/code_2C050]
      - [0x4FAD0, .rodata, kernel/code_2D490]
      - [0x4FC50, .rodata, kernel/code_2EEA0]
      - [0x500B0, .rodata, kernel/code_2FE40]
      - [0x500E0, .rodata, kernel/code_30EA0]
      - [0x500F0, .rodata, kernel/code_310E0]
      - [0x502D0, .rodata, kernel/code_32480]
      - [0x502F0, .rodata, kernel/code_32590]
      - [0x50300, .rodata, kernel/code_32A70]
      - [0x50490, .rodata, kernel/code_35800]
      - [0x504D0, .rodata, kernel/code_35F10]
      - [0x50710, .rodata, kernel/code_37CB0]
      - [0x50720, .rodata, kernel/code_384E0]
      - [0x50730, .rodata, kernel/code_39100]
      - [0x50740, .rodata, kernel/code_3E140]
      - [0x50A00, .rodata, kernel/code_3FB90]
      - [0x50A10, .rodata, kernel/code_3FD10]
      - [0x50A50, .rodata, kernel/code_407C0]
      - [0x50A80, .rodata, kernel/code_41CB0]
      - [0x50AD0, .rodata, kernel/code_41FB0]
      - [0x50B30, .rodata, kernel/code_44B20]
      - [0x50B40, .rodata, kernel/code_45820]
      - [0x50B70, rodata]
      - [0x51370, rodata]
      - [0x51B70, rodata]

  - name: app
    type: code
    start: 0x51e30
    vram: 0x802ca900
    subsegments:
      - [0x51E30, c, app/code_51E30]
      - [0x52230, c, app/code_52230]
      - [0x556C0, c, app/code_556C0]
      - [0x560D0, c, app/code_560D0]
      - [0x58120, c, app/code_58120]
      - [0x58B00, c, app/code_58B00]
      - [0x597E0, c, app/code_597E0]
      - [0x59D80, c, app/code_59D80]
      - [0x5A6A0, c, app/code_5A6A0]
      - [0x5CFC0, c, app/code_5CFC0]
      - [0x60020, asm, app/code_60020]
      - [0x61A60, asm, app/code_61A60]
      - [0x64070, asm, app/code_64070]
      - [0x64730, asm, app/code_64730]
      - [0x66160, c, app/code_66160]
      - [0x68220, c, app/code_68220]
      - [0x69BF0, c, app/code_69BF0]
      - [0x6ACE0, c, app/code_6ACE0]
      - [0x6DAA0, asm, app/code_6DAA0]
      - [0x6FFB0, asm, app/code_6FFB0]
      - [0x72010, c, app/code_72010]
      - [0x722D0, c, app/code_722D0]
      - [0x72910, asm, app/code_72910]
      - [0x76670, c, app/code_76670]
      - [0x78620, c, app/code_78620]
      - [0x796C0, c, app/code_796C0]
      - [0x7B9A0, asm, app/code_7B9A0]
      - [0x7C4C0, asm, app/code_7C4C0]
      - [0x7CF30, asm, app/code_7CF30]
      - [0x81490, asm, app/code_81490]
      - [0x82B90, asm, app/code_82B90]
      - [0x8A760, asm, app/code_8A760]
      - [0x91670, c, app/code_91670]
      - [0x92810, c, app/code_92810]
      - [0x92BF0, asm, app/code_92BF0]
      - [0x936F0, c, app/code_936F0]
      - [0x94E60, c, app/code_94E60]
      - [0x97350, c, app/code_97350]
      - [0x99D40, c, app/code_99D40]
      - [0x9A960, c, app/code_9A960]
      - [0x9B960, c, app/code_9B960]
      - [0x9C080, c, app/code_9C080]
      - [0x9CF50, c, app/code_9CF50]
      - [0x9D3C0, c, app/code_9D3C0]
      - [0x9E2F0, c, app/code_9E2F0]
      - [0x9F2D0, c, app/code_9F2D0]
      - [0xA6000, asm, app/code_A6000]
      - [0xA64C0, asm, app/code_A64C0]
      - [0xA7460, asm, app/code_A7460]
      - [0xA7F20, asm, app/code_A7F20]
      - [0xA8630, asm, app/code_A8630]
      - [0xA8C30, asm, app/code_A8C30]
      - [0xA9D00, c, app/code_A9D00]
      - [0xAA820, asm, app/code_AA820]
      - [0xAE460, c, app/code_AE460]
      - [0xAF950, c, app/code_AF950]
      - [0xB1B30, c, app/code_B1B30]
      - [0xB2900, c, app/code_B2900]
      - [0xB3A70, c, app/code_B3A70]
      - [0xB5280, asm, app/code_B5280]
      - [0xB6580, asm, app/code_B6580]
      - [0xB6FE0, asm, app/code_B6FE0]
      - [0xBADE0, c, app/code_BADE0]
      - [0xBB820, c, app/code_BB820]
      - [0xBD670, c, app/code_BD670]
      - [0xBDAD0, asm, app/code_BDAD0]
      - [0xC6B70, c, app/code_C6B70]
      - [0xC7370, asm, app/code_C7370]
      - [0xC7B40, asm, app/code_C7B40]
      - [0xC9440, c, app/code_C9440]
      - [0xC9B60, c, app/code_C9B60]
      - [0xCB7C0, c, app/code_CB7C0]
      - [0xCBEE0, c, app/code_CBEE0]
      - [0xCD9D0, c, app/code_CD9D0]
      - [0xCDB20, c, app/code_CDB20]
      - [0xCE4F0, asm, app/code_CE4F0]
      - [0xD2B10, asm, app/code_D2B10]
      - [0xD3810, c, app/code_D3810]
      - [0xD4290, c, app/code_D4290]

      - [0xD5C40, data]
      - [0xD5CD0, data]
      - [0xD5D40, data]
      - [0xD5D50, data]
      - [0xD5F10, data]
      - [0xD5F20, data]
      - [0xD5F40, data]
      - [0xD5F60, data]
      - [0xD5F70, data]
      - [0xD6030, data]
      - [0xD62D0, data]
      - [0xD62F0, data]
      - [0xD6360, data]
      - [0xD6410, data]
      - [0xD6450, data]
      - [0xD64D0, data]
      - [0xD64E0, data]
      - [0xD6510, data]
      - [0xD6540, data]
      - [0xD65F0, data]
      - [0xD6650, data]
      - [0xD6660, data]
      - [0xD6680, data]
      - [0xD6690, data]
      - [0xD66E0, data]
      - [0xD66F0, data]
      - [0xD6800, data]
      - [0xD68B0, data]
      - [0xD68C0, data]
      - [0xD68D0, data]
      - [0xD68E0, data]
      - [0xD6910, data]
      - [0xD6920, data]
      - [0xD6930, data]
      - [0xD6980, data]
      - [0xD6CD0, data]
      - [0xD6D20, data]
      - [0xD6D80, data]
      - [0xD6D90, data]
      - [0xD6DC0, data]
      - [0xD6DE0, data]
      - [0xD6E00, data]
      - [0xD6E30, data]
      - [0xD6E40, data]
      - [0xD6EA0, data]
      - [0xD6EB0, data]
      - [0xD7000, data]
      - [0xD7010, data]
      - [0xD70D0, data]
      - [0xD70E0, data]
      - [0xD7100, data]
      - [0xD7140, data]
      - [0xD73B0, data]
      - [0xD7500, data]
      - [0xD7980, data]
      - [0xD7990, data]
      - [0xD79C0, data]
      - [0xD79E0, data]
      - [0xD7A30, data]
      - [0xD7A40, data]
      - [0xD7A90, data]
      - [0xD7AE0, data]
      - [0xD7AF0, data]
      - [0xD7B80, data]
      - [0xD7BC0, data]
      - [0xD7D20, data]
      - [0xD7E10, data]
      - [0xD7EF0, data]
      - [0xD7F20, .rodata, app/code_51E30]
      - [0xD7F60, .rodata, app/code_52230]
      - [0xD8340, .rodata, app/code_556C0]
      - [0xD83B0, .rodata, app/code_560D0]
      - [0xD84A0, .rodata, app/code_58120]
      - [0xD8590, .rodata, app/code_58B00]
      - [0xD85D0, .rodata, app/code_597E0]
      - [0xD8610, .rodata, app/code_59D80]
      - [0xD8670, .rodata, app/code_5A6A0]
      - [0xD8730, .rodata, app/code_5CFC0]
      - [0xD8980, rodata, app/code_60020]
#     - [0xD8A00, rodata, app/code_60020] # app/code_61A60
      - [0xD8B90, rodata, app/code_64070] # app/code_64730
      - [0xD8CE0, .rodata, app/code_66160]
      - [0xD8DD0, .rodata, app/code_68220]
      - [0xD9080, .rodata, app/code_69BF0]
      - [0xD91E0, .rodata, app/code_6ACE0]
      - [0xD9360, rodata, app/code_6DAA0]
#     - [0xD94F0, rodata, app/code_6DAA0]
#     - [0xD9510, rodata, app/code_6DAA0]
      - [0xD95D0, rodata, app/code_6FFB0]
      - [0xD95F0, .rodata, app/code_722D0]
      - [0xD9830, rodata, app/code_72910]
#     - [0xD9840, rodata, app/code_72910]
#     - [0xD99C0, rodata, app/code_72910]
      - [0xD9A10, .rodata, app/code_76670]
      - [0xD9CF0, .rodata, app/code_78620]
      - [0xD9DF0, .rodata, app/code_796C0]
      - [0xD9F20, rodata, app/code_7B9A0] # app/code_7C4C0
      - [0xDA020, rodata, app/code_7CF30]
#     - [0xDA4F0, rodata, app/code_7CF30]
      - [0xDA640, rodata, app/code_81490]
#     - [0xDA7C0, rodata, app/code_81490] # app/code_82B90
      - [0xDABB0, rodata, app/code_8A760]
#     - [0xDADB0, rodata, app/code_8A760]
      - [0xDAE00, .rodata, app/code_91670]
      - [0xDAF00, .rodata, app/code_92810]
      - [0xDB1D0, .rodata, app/code_936F0]
      - [0xDB750, .rodata, app/code_94E60]
      - [0xDB770, .rodata, app/code_97350]
      - [0xDB9B0, .rodata, app/code_99D40]
      - [0xDBA00, .rodata, app/code_9A960]
      - [0xDBA30, .rodata, app/code_9B960]
      - [0xDBA60, .rodata, app/code_9C080]
      - [0xDBA90, .rodata, app/code_9D3C0]
      - [0xDBB00, .rodata, app/code_9E2F0]
      - [0xDBC60, .rodata, app/code_9F2D0]
      - [0xDBE30, rodata, app/code_A6000] # app/code_A64C0 app/code_A7460
      - [0xDC000, rodata, app/code_A7F20] # app/code_A8630 app/code_A8C30
      - [0xDC2F0, .rodata, app/code_A9D00]
      - [0xDC3C0, rodata, app/code_AA820]
#     - [0xDC4D0, rodata, app/code_AA820]
      - [0xDC800, .rodata, app/code_AE460]
      - [0xDC8C0, .rodata, app/code_AF950]
      - [0xDC9F0, .rodata, app/code_B1B30]
      - [0xDCAF0, .rodata, app/code_B2900]
      - [0xDCB20, .rodata, app/code_B3A70]
      - [0xDCBE0, rodata, app/code_B5280] # app/code_B6580
      - [0xDD260, rodata, app/code_B6FE0]
#     - [0xDD550, rodata, app/code_B6FE0]
      - [0xDD5B0, .rodata, app/code_BADE0]
      - [0xDD680, .rodata, app/code_BB820]
      - [0xDD6D0, .rodata, app/code_BD670]
      - [0xDD740, rodata, app/code_BDAD0]
#     - [0xDDA90, rodata, app/code_BDAD0]
      - [0xDDC80, .rodata, app/code_C6B70]
      - [0xDDDA0, rodata, app/code_C7B40]
#     - [0xDDEA0, rodata, app/code_C7B40]
      - [0xDDF40, .rodata, app/code_C9B60]
      - [0xDDFB0, .rodata, app/code_CB7C0]
      - [0xDE020, .rodata, app/code_CBEE0]
      - [0xDE210, .rodata, app/code_CDB20]
      - [0xDE250, rodata, app/code_CE4F0]
#     - [0xDE4A0, rodata, app/code_CE4F0]
#     - [0xDE550, rodata, app/code_CE4F0]
      - [0xDE5A0, rodata, app/code_D2B10]
#     - [0xDE5F0, rodata, app/code_D2B10]
      - [0xDE600, .rodata, app/code_D3810]
      - [0xDE640, .rodata, app/code_D4290]

  - name: bin_DE6B0
    type: bin
    start: 0xDE6B0

  - [0x800000]
