name: Pilot Wings64 (North America)
sha1: ec771aedf54ee1b214c25404fb4ec51cfd43191a
options:
  basename: pilotwings64
  target_path: config/us/baserom.us.z64
  elf_path: build/pilotwings64.elf
  base_path: ../..
  platform: n64
  compiler: IDO

  asm_path: asm
  src_path: src
  asset_path: bin
  build_path: build
  create_asm_dependencies: True
  asm_emit_size_directive: True
  disasm_unknown: True

  ld_script_path: build/pilotwings64.us.ld
  ld_dependencies: True

  find_file_boundaries: True
  header_encoding: ASCII

  o_as_suffix: True
  use_legacy_include_asm: False
  mips_abi_float_regs: o32

  # section_order: [".text", ".data", ".rodata", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/us/sym/symbol_addrs.txt
    - config/us/sym/libultra_symbols.txt
  reloc_addrs_path:
    - config/us/sym/reloc_addrs.txt

  undefined_funcs_auto_path: build/splat_out/us/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/splat_out/us/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  # string_encoding: ASCII
  # data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  libultra_symbols: True
  hardware_regs: True
  gfx_ucode: f3d
  migrate_rodata_to_functions: True

segments:
  - name: header
    type: header
    start: 0x0

  - name: ipl3
    type: bin
    start: 0x40

  - name: entry
    type: code
    start: 0x1000
    vram: 0x80200050
    subsegments:
      - [0x1000, hasm, entrypoint]

  - name: main
    type: code
    start: 0x1050
    vram: 0x802000A0
    follows_vram: entry
    subsegments:
      - [0x1050, c, game/code_1050]
      - [0x1300, c, game/code_1300]
      - [0x2130, c, game/code_2130]
      - [0x3D50, c, game/code_3D50]
      - [0x4850, c, game/code_4850]
      - [0x5690, c, game/code_5690]
      - [0x58E0, c, game/code_58E0]
      - [0x6F80, c, game/code_6F80]
      - [0x7150, c, game/code_7150]
      - [0x8170, c, game/code_8170]
      - [0x177A0, c, game/code_177A0]
      - [0x19B50, c, game/code_19B50]
      - [0x1AF80, c, game/code_1AF80]
      - [0x200B0, c, game/code_200B0]
      - [0x21910, c, game/code_21910]
      - [0x25250, c, game/code_25250]
      - [0x25650, c, game/code_25650]
      - [0x28EE0, c, game/code_28EE0]
      - [0x2AE50, c, game/code_2AE50]
      - [0x2B370, c, game/code_2B370]
      - [0x2C050, c, game/code_2C050]
      - [0x2EEA0, c, game/code_2EEA0]
      - [0x2FE40, c, game/code_2FE40]
      - [0x30DF0, c, game/code_30DF0]
      - [0x30EA0, c, game/code_30EA0]
      - [0x32480, c, game/code_32480]
      - [0x32590, c, game/code_32590]
      - [0x329C0, hasm, game/code_329C0]
      - [0x32A70, c, game/code_32A70]
      - [0x35450, c, game/code_35450]
      - [0x35470, c, game/code_35470]
      - [0x354E0, c, game/code_354E0]
      - [0x355D0, c, game/code_355D0]
      - [0x35640, c, game/code_35640]
      - [0x356A0, c, game/code_356A0]
      - [0x35700, c, game/code_35700]
      - [0x35760, c, game/code_35760]
      - [0x357C0, c, game/code_357C0]
      - [0x35800, c, game/code_35800]
      - [0x35F10, c, game/code_35F10]
      - [0x37140, c, game/code_37140]
      - [0x37290, c, game/code_37290]
      - [0x372F0, c, game/code_372F0]
      - [0x37540, c, game/code_37540]
      - [0x37790, c, game/code_37790]
      - [0x378E0, c, game/code_378E0]
      - [0x37B70, c, game/code_37B70]
      - [0x37BF0, c, game/code_37BF0]
      - [0x37CA0, c, game/code_37CA0]
      - [0x37CB0, c, game/code_37CB0]
      - [0x38490, c, game/code_38490]
      - [0x384D0, c, game/code_384D0]
      - [0x384E0, c, game/code_384E0]
      - [0x38FA0, c, game/code_38FA0]
      - [0x38FE0, c, game/code_38FE0]
      - [0x39080, c, game/code_39080]
      - [0x390C0, c, game/code_390C0]
      - [0x39100, c, game/code_39100]
      - [0x3B730, c, game/code_3B730]
      - [0x3B760, c, game/code_3B760]
      - [0x3B7D0, c, game/code_3B7D0]
      - [0x3B7E0, c, game/code_3B7E0]
      - [0x3B8D0, c, game/code_3B8D0]
      - [0x3BA90, c, game/code_3BA90]
      - [0x3BDD0, c, game/code_3BDD0]
      - [0x3BE50, c, game/code_3BE50]
      - [0x3C110, c, game/code_3C110]
      - [0x3C4F0, c, game/code_3C4F0]
      - [0x3C560, c, game/code_3C560]
      - [0x3C5D0, c, game/code_3C5D0]
      - [0x3C640, c, game/code_3C640]
      - [0x3C820, c, game/code_3C820]
      - [0x3C960, c, game/code_3C960]
      - [0x3C9D0, c, game/code_3C9D0]
      - [0x3CC60, c, game/code_3CC60]
      - [0x3CC70, c, game/code_3CC70]
      - [0x3CDF0, c, game/code_3CDF0]
      - [0x3CFB0, c, game/code_3CFB0]
      - [0x3D5D0, c, game/code_3D5D0]
      - [0x3D680, c, game/code_3D680]
      - [0x3D810, c, game/code_3D810]
      - [0x3DDD0, c, game/code_3DDD0]
      - [0x3DE60, c, game/code_3DE60]
      - [0x3DEF0, c, game/code_3DEF0]
      - [0x3DF90, c, game/code_3DF90]
      - [0x3E020, c, game/code_3E020]
      - [0x3E0C0, c, game/code_3E0C0]
      - [0x3E140, c, game/code_3E140]
      - [0x3FB90, c, game/code_3FB90]
      - [0x3FCD0, c, game/code_3FCD0]
      - [0x3FD10, c, game/code_3FD10]
      - [0x406F0, c, game/code_406F0]
      - [0x40700, c, game/code_40700]
      - [0x407C0, c, game/code_407C0]
      - [0x40F70, c, game/code_40F70]
      - [0x41010, c, game/code_41010]
      - [0x41CB0, c, game/code_41CB0]
      - [0x41FB0, c, game/code_41FB0]
      - [0x42C10, c, game/code_42C10]
      - [0x42D20, c, game/code_42D20]
      - [0x42F60, c, game/code_42F60]
      - [0x42F80, c, game/code_42F80]
      - [0x43360, c, game/code_43360]
      - [0x43370, c, game/code_43370]
      - [0x433B0, c, game/code_433B0]
      - [0x43440, c, game/code_43440]
      - [0x43470, c, game/code_43470]
      - [0x43890, c, game/code_43890]
      - [0x438A0, c, game/code_438A0]
      - [0x43C00, c, game/code_43C00]
      - [0x43C10, c, game/code_43C10]
      - [0x443F0, c, game/code_443F0]
      - [0x444D0, c, game/code_444D0]
      - [0x44580, c, game/code_44580]
      - [0x44600, c, game/code_44600]
      - [0x44660, c, game/code_44660]
      - [0x44700, c, game/code_44700]
      - [0x44960, c, game/code_44960]
      - [0x449F0, c, game/code_449F0]
      - [0x44AA0, c, game/code_44AA0]
      - [0x44B20, c, game/code_44B20]
      - [0x455D0, c, game/code_455D0]
      - [0x45700, c, game/code_45700]
      - [0x45800, c, game/code_45800]
      - [0x45820, c, game/code_45820]
      - [0x46430, c, game/code_46430]
      - [0x46440, c, game/code_46440]
      - [0x46470, c, game/code_46470]
      - [0x46480, c, game/code_46480]
      - [0x464E0, data]

      - [0x4D500, .rodata, game/code_1050]
      - [0x4D540, .rodata, game/code_1300]
      - [0x4D5E0, .rodata, game/code_2130]
      - [0x4DBF0, .rodata, game/code_3D50]
      - [0x4DC90, .rodata, game/code_4850]
      - [0x4DCE0, .rodata, game/code_5690]
      - [0x4DD10, .rodata, game/code_58E0]
      - [0x4DDC0, .rodata, game/code_6F80]
      - [0x4DDF0, .rodata, game/code_7150]
      - [0x4DE10, .rodata, game/code_8170]
      - [0x4E370, .rodata, game/code_177A0]
      # - [0x4E780, .rodata, game/code_19B50]
      # - [0x4E870, .rodata, game/code_1AF80]
      # - [0x4EB30, .rodata, game/code_200B0]
      # - [0x4EBD0, .rodata, game/code_21910]
      # - [0x4EF20, .rodata, game/code_25250]
      # - [0x4EF70, .rodata, game/code_25650]
      # - [0x4F280, .rodata, game/code_28EE0]
      # - [0x4F350, .rodata, game/code_2AE50]
      # - [0x2B370, c, game/code_2B370]
      # - [0x2C050, c, game/code_2C050]
      # - [0x2EEA0, c, game/code_2EEA0]
      # - [0x2FE40, c, game/code_2FE40]
      # - [0x30DF0, c, game/code_30DF0]
      # - [0x30EA0, c, game/code_30EA0]
      # - [0x32480, c, game/code_32480]
      # - [0x32590, c, game/code_32590]

  - type: bin
    start: 0x4E620
    follows_vram: main

  - [0x800000]
